### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m2-evaluacion-intermedia-Mariasola#1]
Really cool job @Mariasola !!!

Here you have some tips to improve the exercise:

https://github.com/Adalab/m2-evaluacion-intermedia-Mariasola/blob/master/main.js#L31 >>> WooooW!!!!  ;)

### JavaScript

- [x] Delete unused functions https://github.com/Adalab/m2-evaluacion-intermedia-Mariasola/blob/master/main.js#L48

### JavaScript - Good practices

- [x] Move variables and constants declarations to the top of the file

### Good practices

- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

### Structure

- [x] Define a good structure of folders and files for the project

### HTML

- [x] Add HTML elements for the game: form, title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [ ] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Si me conviertes este array en un objeto te prometo que expongo tú código en el louvre!!!! 

![](https://media.giphy.com/media/cGEWR5jiq9AWc/giphy.gif)

**Comment by mariasola** [comment]
Listo!
